UNITS_DESC = {
        'ping':{
            'id':1,
            'cost':1,
            'stability':15,
            'range':3.5,
            'dpf':1,
            'speed':2
            },
        'emp':{
            'id':2,
            'cost':3,
            'stability':5,
            'range':5.5,
            'dpf':3,
            'speed':4
            },
        'scrambler':{
            'id':3,
            'cost':1,
            'stability':40,
            'range':3.5,
            'dpf':10,
            'speed':4
            },
        'filter':{
            'id':4,
            'cost':1,
            'stability':60,
            'range':0,
            'dpf':0,
            'speed':0
            },
        'encryptor':{
            'id':5,
            'cost':4,
            'stability':30,
            'range':3.5,
            'dpf':0,
            'speed':0
            },
        'destructor':{
            'id':6,
            'cost':3,
            'stability':75,
            'range':3.5,
            'dpf':4,
            'speed':0,
            }
        }


