sudo: required
language: python
python:
  - 3.6
  
before_install:
    - pip install pytest pytest-cov
    - pip install matplotlib
    - pip install coveralls
    - pip install codecov

install:
    - python setup.py install

script: py.test --cov=tc1 tests/

after_success:
    - coveralls
    - codecov

notifications:
  email: false
