sudo: required
language: python
python:
  - 3.4
  
before_install:
    - pip install pytest pytest-cov
    - pip install matplotlib
    - pip install celluloid
    - pip install coveralls

install:
  - python setup.py install

script: pytest

notifications:
  email: false
