sudo: required
language: python
python:
  - 3.4
  
before_install:
    - pip install pytest pytest-cov
    - pip install matplotlib
    - pip install coveralls

script: pytest

notifications:
  email: false
