sudo: required
language: python
python:
  - 3.6
  
before_install:
    - pip install pytest pytest-cov
    - pip install matplotlib
    - pip install coveralls

install:
    - python setup.py install

script: py.test --cov

after_success:
    - coveralls

notifications:
  email: false
